service: frontend-service
handlers:
- url: /weather
  script: auto
- url: /about
  script: auto
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /static
  static_dir: public
